### ISSUE TITLE
how to find Post.media.gif ?

### ISSUE THREAD

**Issue by AktilaCengiz** [Jinzulen/TenorJS#5]
Hello dear creator!
I'm gonna ask you to help me with something I can't do.
My problem is: we pull the post from the results. media in post. I want to pull the gif to media but after "post.media" I can't pull the [objects] in it.

1-`Tenor.Search.Random("anime hug", "1").then(Results => {
      Results.forEach(Post => {`
2-`var mediax = Post.media` okey we see console.log then see medias but
3- `var gif = mediax.gif` finally wee saw error or undefined
i saw undefined.

Can you help me with how? Is there a mistake in me I wasn't sure?

**Screenshots**
![Adsız](https://user-images.githubusercontent.com/49373230/60323921-0d5a3e80-998c-11e9-89b1-41b771d4f62c.png)
![Adsız2](https://user-images.githubusercontent.com/49373230/60323923-0d5a3e80-998c-11e9-9af2-0c9925f55809.png)

**Comment by AktilaCengiz** [comment]
gif is found in the media but is not withdrawn.

**Comment by Jinzulen** [comment]
The "media" object is an array, to pull anything from it you first need to access the first key.

```
var mediax = Post.media[0];
console.log(mediax.gif);
```

**Comment by AktilaCengiz** [comment]
Thank you! It is working.

**Comment by Jinzulen** [comment]
Glad to hear that, good luck with your project. 😄👌
